workflows:
  build-appinsight-android:
    name: Build AppInsight Android APK
    max_build_duration: 30
    instance_type: mac_mini
    environment:
      vars:
        PACKAGE_NAME: "com.example.appinsight"
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web assets
        script: |
          npm run build
      - name: Capacitor Sync
        script: |
          npx cap sync android
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
